---
title: "Demographic_robust"
author: "Manu"
date: "January 18, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Preprocessing

Load clean and preprocess the file to create the three required variables:

1. Size of household (size)
2. Gender ratio of household (gender)
3. Age pyramid- (Age)

As the NRVA dataset being used now is about 3 years old infants younger than 3 and adults older than 55 are excluded from the sample.
```{r}

df = read.csv("C:\\Users\\ms52\\Dropbox (ESOC - Princeton)\\High-Rez Indicators\\Data\\Sayara\\baseline\\highRez_baseline_hhroster.csv")

head(df)
d = df

## subtract 3 from everybodays age
df$Q_1_06_ = df$Q_1_06_ - 3 


#Exclude children and very old ppl
df<-df[!(df$Q_1_06_ < 0 | df$Q_1_06_ > 55),]


df$male = ifelse(df$Q_1_05_ =="Male",1,0)
df$female = ifelse(df$Q_1_05_ =="Female",1,0)
#total males
a = as.data.frame (tapply(df$male, df$respid, FUN = sum))
a$respid = rownames(a)
colnames(a) = c("tot_male", "respid")
head(a)
#total females
b = as.data.frame (tapply(df$female, df$respid, FUN = sum))

b$respid = rownames(b)
colnames(b) = c("tot_female", "respid")
head(b)

temp = merge(a, b, by = "respid")
temp$gender_ratio = temp$tot_male/temp$tot_female

head(temp)

df = merge (temp, df, by = "respid")
```


```{r}

###Calculating Household sizes

library(plyr)
head(df)
a = count(df, "respid")
df = merge(a, df, by = "respid")
```


```{r}
##### processing data for comparison with NRVA


#age Pyramid
df$age_bracket <- as.factor( as.numeric( cut(df$Q_1_06_,breaks = seq(0, 55, by = 5))))

a = as.data.frame(table(df$age_bracket))

write.csv(a, file = "age_pyr_BL.csv")

##combine features from both the files and display
file = choose.files()
total = read.csv("C:\\Users\\ms52\\Dropbox (ESOC - Princeton)\\High-Rez Indicators\\Analysis\\Prelim_robustness\\age_pyr_total.csv")

```

```{r}
#Reshaping and plotting data
library(reshape2)

melt =  melt(total, id = c("X"))
head(melt)
melt$value = ifelse(melt$variable =="NRVA",melt$value*-1,melt$value)


library(ggplot2)


 ggplot(data=melt,aes(x=X, y = value,fill=variable)) + 
  geom_bar(data=melt[melt[["variable"]] =="NRVA",], stat = "identity" )+
  geom_bar(data=melt[melt[["variable"]] == "BASE_LINE",] , stat = "identity") +   scale_y_continuous(breaks=seq(-40,40,2),labels=abs(seq(-40,40,2)))+coord_flip()+scale_fill_brewer(palette = "Set1") +theme_bw()




````
